import mongoose from 'mongoose'
import bcrypt from 'bcryptjs'
import { connectDB } from './connect'
import User from '../models/User'
import ProxyProduct from '../models/ProxyProduct'
import type { ProxyProductDocument } from '../models/ProxyProduct'
import UserProxy from '../models/UserProxy'
import Order from '../models/Order'

function plans(prices: [string, string, string, string, string, string], ips: [number,number,number,number,number,number]) {
  return [
    { duration: '1d',   ipCount: ips[0], priceUsdt: mongoose.Types.Decimal128.fromString(prices[0]), discount: 0,  isPopular: false },
    { duration: '7d',   ipCount: ips[1], priceUsdt: mongoose.Types.Decimal128.fromString(prices[1]), discount: 0,  isPopular: false },
    { duration: '30d',  ipCount: ips[2], priceUsdt: mongoose.Types.Decimal128.fromString(prices[2]), discount: 10, isPopular: true  },
    { duration: '90d',  ipCount: ips[3], priceUsdt: mongoose.Types.Decimal128.fromString(prices[3]), discount: 15, isPopular: false },
    { duration: '180d', ipCount: ips[4], priceUsdt: mongoose.Types.Decimal128.fromString(prices[4]), discount: 20, isPopular: false },
    { duration: '1y',   ipCount: ips[5], priceUsdt: mongoose.Types.Decimal128.fromString(prices[5]), discount: 25, isPopular: false },
  ]
}

function res(code: string, name: string, city: string, isp: string, speed: number, uptime: number, p30: number) {
  const f = (n: number) => n.toFixed(2)
  return {
    name: `${code} Residential`,
    description: `${name} residential proxies from ${city}. Real ${isp} addresses for accurate geo-targeting and local market access.`,
    type: 'residential',
    protocols: ['http', 'https', 'socks5'],
    countryCode: code,
    countryName: name,
    city,
    ispName: isp,
    speedMbps: speed,
    uptimePercent: uptime,
    stock: -1,
    isActive: true,
    isFeatured: false,
    tags: ['residential', code.toLowerCase()],
    plans: [
      { duration: '1d',   ipCount: 5,   priceUsdt: mongoose.Types.Decimal128.fromString(f(p30 / 8)),   discount: 0,  isPopular: false },
      { duration: '7d',   ipCount: 5,   priceUsdt: mongoose.Types.Decimal128.fromString(f(p30 / 3.3)), discount: 0,  isPopular: false },
      { duration: '30d',  ipCount: 10,  priceUsdt: mongoose.Types.Decimal128.fromString(f(p30)),        discount: 10, isPopular: true  },
      { duration: '90d',  ipCount: 25,  priceUsdt: mongoose.Types.Decimal128.fromString(f(p30 * 2.4)), discount: 15, isPopular: false },
      { duration: '180d', ipCount: 50,  priceUsdt: mongoose.Types.Decimal128.fromString(f(p30 * 4.4)), discount: 20, isPopular: false },
      { duration: '1y',   ipCount: 100, priceUsdt: mongoose.Types.Decimal128.fromString(f(p30 * 7.5)), discount: 25, isPopular: false },
    ],
  }
}

const PRODUCTS_SEED = [
  // ─── NORTH AMERICA ───────────────────────────────────────────
  {
    name: 'US Residential Premium',
    description: 'High-quality US residential proxies with real ISP IPs. Perfect for social media, ad verification, and scraping.',
    type: 'residential',
    protocols: ['http', 'https', 'socks5'],
    countryCode: 'US',
    countryName: 'United States',
    city: 'New York',
    ispName: 'Comcast',
    speedMbps: 100,
    uptimePercent: 99.5,
    stock: -1,
    isActive: true,
    isFeatured: true,
    tags: ['residential', 'premium', 'usa', 'unlimited'],
    plans: [
      { duration: '1d', ipCount: 5, priceUsdt: mongoose.Types.Decimal128.fromString('4.99'), discount: 0, isPopular: false },
      { duration: '7d', ipCount: 5, priceUsdt: mongoose.Types.Decimal128.fromString('14.99'), discount: 0, isPopular: false },
      { duration: '30d', ipCount: 10, priceUsdt: mongoose.Types.Decimal128.fromString('39.99'), discount: 10, isPopular: true },
      { duration: '90d', ipCount: 25, priceUsdt: mongoose.Types.Decimal128.fromString('99.99'), discount: 15, isPopular: false },
      { duration: '180d', ipCount: 50, priceUsdt: mongoose.Types.Decimal128.fromString('179.99'), discount: 20, isPopular: false },
      { duration: '1y', ipCount: 100, priceUsdt: mongoose.Types.Decimal128.fromString('299.99'), discount: 25, isPopular: false },
    ],
  },
  {
    name: 'DE Datacenter Fast',
    description: 'Ultra-fast German datacenter proxies. Ideal for SEO monitoring, data collection, and automated tasks.',
    type: 'datacenter',
    protocols: ['http', 'https', 'socks5'],
    countryCode: 'DE',
    countryName: 'Germany',
    city: 'Frankfurt',
    ispName: 'Hetzner',
    speedMbps: 1000,
    uptimePercent: 99.9,
    stock: 500,
    isActive: true,
    isFeatured: true,
    tags: ['datacenter', 'fast', 'germany', 'dedicated'],
    plans: [
      { duration: '1d', ipCount: 10, priceUsdt: mongoose.Types.Decimal128.fromString('2.99'), discount: 0, isPopular: false },
      { duration: '7d', ipCount: 10, priceUsdt: mongoose.Types.Decimal128.fromString('9.99'), discount: 0, isPopular: false },
      { duration: '30d', ipCount: 25, priceUsdt: mongoose.Types.Decimal128.fromString('24.99'), discount: 5, isPopular: true },
      { duration: '90d', ipCount: 50, priceUsdt: mongoose.Types.Decimal128.fromString('64.99'), discount: 10, isPopular: false },
      { duration: '180d', ipCount: 100, priceUsdt: mongoose.Types.Decimal128.fromString('119.99'), discount: 15, isPopular: false },
      { duration: '1y', ipCount: 200, priceUsdt: mongoose.Types.Decimal128.fromString('199.99'), discount: 20, isPopular: false },
    ],
  },
  {
    name: 'GB Mobile 4G/5G',
    description: 'UK mobile proxies on real 4G/5G networks. Best for mobile app testing and high-trust operations.',
    type: 'mobile',
    protocols: ['http', 'https', 'socks5'],
    countryCode: 'GB',
    countryName: 'United Kingdom',
    city: 'London',
    ispName: 'EE Mobile',
    speedMbps: 50,
    uptimePercent: 98.5,
    stock: 200,
    isActive: true,
    isFeatured: false,
    tags: ['mobile', '4g', '5g', 'uk'],
    plans: [
      { duration: '1d', ipCount: 2, priceUsdt: mongoose.Types.Decimal128.fromString('7.99'), discount: 0, isPopular: false },
      { duration: '7d', ipCount: 5, priceUsdt: mongoose.Types.Decimal128.fromString('24.99'), discount: 0, isPopular: false },
      { duration: '30d', ipCount: 10, priceUsdt: mongoose.Types.Decimal128.fromString('79.99'), discount: 10, isPopular: true },
      { duration: '90d', ipCount: 20, priceUsdt: mongoose.Types.Decimal128.fromString('199.99'), discount: 15, isPopular: false },
    ],
  },
  {
    name: 'NL ISP Residential',
    description: 'Netherlands ISP proxies — combination of datacenter speed with residential trust level.',
    type: 'isp',
    protocols: ['http', 'https'],
    countryCode: 'NL',
    countryName: 'Netherlands',
    city: 'Amsterdam',
    ispName: 'KPN',
    speedMbps: 500,
    uptimePercent: 99.7,
    stock: 300,
    isActive: true,
    isFeatured: false,
    tags: ['isp', 'netherlands', 'residential-speed', 'reliable'],
    plans: [
      { duration: '7d', ipCount: 5, priceUsdt: mongoose.Types.Decimal128.fromString('12.99'), discount: 0, isPopular: false },
      { duration: '30d', ipCount: 10, priceUsdt: mongoose.Types.Decimal128.fromString('34.99'), discount: 8, isPopular: true },
      { duration: '90d', ipCount: 25, priceUsdt: mongoose.Types.Decimal128.fromString('89.99'), discount: 12, isPopular: false },
      { duration: '180d', ipCount: 50, priceUsdt: mongoose.Types.Decimal128.fromString('159.99'), discount: 18, isPopular: false },
      { duration: '1y', ipCount: 100, priceUsdt: mongoose.Types.Decimal128.fromString('269.99'), discount: 22, isPopular: false },
    ],
  },
  {
    name: 'FR Residential Rotating',
    description: 'French rotating residential proxies. Auto-rotate on each request for maximum anonymity.',
    type: 'residential',
    protocols: ['http', 'https', 'socks5'],
    countryCode: 'FR',
    countryName: 'France',
    city: 'Paris',
    ispName: 'Orange',
    speedMbps: 80,
    uptimePercent: 99.2,
    stock: -1,
    isActive: true,
    isFeatured: false,
    tags: ['residential', 'rotating', 'france', 'paris'],
    plans: [
      { duration: '1d', ipCount: 10, priceUsdt: mongoose.Types.Decimal128.fromString('6.99'), discount: 0, isPopular: false },
      { duration: '30d', ipCount: 50, priceUsdt: mongoose.Types.Decimal128.fromString('49.99'), discount: 12, isPopular: true },
      { duration: '90d', ipCount: 100, priceUsdt: mongoose.Types.Decimal128.fromString('129.99'), discount: 18, isPopular: false },
    ],
  },
  {
    name: 'CA Residential',
    description: 'Canadian residential proxies. Ideal for North American geo-targeting, streaming, and e-commerce.',
    type: 'residential', protocols: ['http', 'https', 'socks5'],
    countryCode: 'CA', countryName: 'Canada', city: 'Toronto', ispName: 'Rogers',
    speedMbps: 90, uptimePercent: 99.4, stock: -1, isActive: true, isFeatured: false,
    tags: ['residential', 'canada', 'north-america'],
    plans: plans(['4.49','13.99','37.99','94.99','169.99','279.99'], [5,5,10,25,50,100]),
  },
  {
    name: 'US Datacenter Bulk',
    description: 'US datacenter proxies for bulk operations. High speed, large IP pools, great for SEO and data mining.',
    type: 'datacenter', protocols: ['http', 'https', 'socks5'],
    countryCode: 'US', countryName: 'United States', city: 'Los Angeles', ispName: 'Limelight',
    speedMbps: 2000, uptimePercent: 99.98, stock: 1000, isActive: true, isFeatured: true,
    tags: ['datacenter', 'usa', 'bulk', 'high-speed'],
    plans: plans(['1.99','6.99','19.99','49.99','89.99','149.99'], [10,25,50,100,200,500]),
  },
  {
    name: 'MX Residential',
    description: 'Mexican residential proxies for LATAM geo-targeting, local content, and regional price monitoring.',
    type: 'residential', protocols: ['http', 'https', 'socks5'],
    countryCode: 'MX', countryName: 'Mexico', city: 'Mexico City', ispName: 'Telmex',
    speedMbps: 60, uptimePercent: 98.8, stock: -1, isActive: true, isFeatured: false,
    tags: ['residential', 'mexico', 'latam'],
    plans: plans(['3.49','10.99','29.99','74.99','134.99','219.99'], [5,5,10,25,50,100]),
  },
  {
    name: 'BR Residential',
    description: 'Brazilian residential proxies for South American operations. Access local content and marketplaces.',
    type: 'residential', protocols: ['http', 'https', 'socks5'],
    countryCode: 'BR', countryName: 'Brazil', city: 'São Paulo', ispName: 'Claro',
    speedMbps: 50, uptimePercent: 98.5, stock: -1, isActive: true, isFeatured: false,
    tags: ['residential', 'brazil', 'south-america'],
    plans: plans(['3.49','10.99','29.99','74.99','134.99','219.99'], [5,5,10,25,50,100]),
  },
  // ─── EUROPE ────────────────────────────────────────────────────
  {
    name: 'JP Datacenter Enterprise',
    description: 'Japanese enterprise datacenter proxies with dedicated IPs. Perfect for Japan-specific services.',
    type: 'datacenter', protocols: ['http', 'https', 'socks5'],
    countryCode: 'JP', countryName: 'Japan', city: 'Tokyo', ispName: 'NTT',
    speedMbps: 2000, uptimePercent: 99.95, stock: 150, isActive: true, isFeatured: true,
    tags: ['datacenter', 'japan', 'enterprise', 'dedicated', 'high-speed'],
    plans: plans(['9.99','24.99','54.99','139.99','249.99','449.99'], [5,10,20,50,100,200]),
  },
  {
    name: 'UA Residential',
    description: 'Ukrainian residential proxies. Real ISP addresses from Kyiv and major cities.',
    type: 'residential', protocols: ['http', 'https', 'socks5'],
    countryCode: 'UA', countryName: 'Ukraine', city: 'Kyiv', ispName: 'Kyivstar',
    speedMbps: 100, uptimePercent: 99.1, stock: -1, isActive: true, isFeatured: true,
    tags: ['residential', 'ukraine', 'eastern-europe'],
    plans: plans(['3.99','11.99','32.99','79.99','144.99','239.99'], [5,5,10,25,50,100]),
  },
  {
    name: 'PL Residential',
    description: 'Polish residential proxies for Central European geo-targeting and local market research.',
    type: 'residential', protocols: ['http', 'https', 'socks5'],
    countryCode: 'PL', countryName: 'Poland', city: 'Warsaw', ispName: 'Orange PL',
    speedMbps: 85, uptimePercent: 99.3, stock: -1, isActive: true, isFeatured: false,
    tags: ['residential', 'poland', 'central-europe'],
    plans: plans(['3.79','11.49','30.99','77.99','139.99','229.99'], [5,5,10,25,50,100]),
  },
  {
    name: 'SE Datacenter',
    description: 'Swedish datacenter proxies. GDPR-compliant infrastructure, ideal for EU operations.',
    type: 'datacenter', protocols: ['http', 'https', 'socks5'],
    countryCode: 'SE', countryName: 'Sweden', city: 'Stockholm', ispName: 'Telia',
    speedMbps: 1000, uptimePercent: 99.9, stock: 400, isActive: true, isFeatured: false,
    tags: ['datacenter', 'sweden', 'scandinavia', 'gdpr'],
    plans: plans(['2.49','7.99','21.99','54.99','99.99','169.99'], [10,25,50,100,200,500]),
  },
  {
    name: 'IT Residential',
    description: 'Italian residential proxies for Mediterranean market access and local price comparison.',
    type: 'residential', protocols: ['http', 'https', 'socks5'],
    countryCode: 'IT', countryName: 'Italy', city: 'Milan', ispName: 'TIM',
    speedMbps: 75, uptimePercent: 99.0, stock: -1, isActive: true, isFeatured: false,
    tags: ['residential', 'italy', 'southern-europe'],
    plans: plans(['4.49','13.99','37.99','94.99','169.99','279.99'], [5,5,10,25,50,100]),
  },
  {
    name: 'ES ISP',
    description: 'Spanish ISP proxies — high-speed with residential-level trust. Perfect for Iberian targeting.',
    type: 'isp', protocols: ['http', 'https'],
    countryCode: 'ES', countryName: 'Spain', city: 'Madrid', ispName: 'Telefonica',
    speedMbps: 600, uptimePercent: 99.6, stock: 250, isActive: true, isFeatured: false,
    tags: ['isp', 'spain', 'iberia', 'high-trust'],
    plans: plans(['5.99','17.99','44.99','109.99','199.99','329.99'], [5,5,10,25,50,100]),
  },
  {
    name: 'CH Datacenter',
    description: 'Swiss datacenter proxies with strict privacy laws. Ideal for finance, banking, and compliance.',
    type: 'datacenter', protocols: ['http', 'https', 'socks5'],
    countryCode: 'CH', countryName: 'Switzerland', city: 'Zurich', ispName: 'Swisscom',
    speedMbps: 1500, uptimePercent: 99.98, stock: 200, isActive: true, isFeatured: false,
    tags: ['datacenter', 'switzerland', 'finance', 'privacy'],
    plans: plans(['3.99','12.99','34.99','84.99','154.99','254.99'], [10,20,40,100,200,400]),
  },
  {
    name: 'RO Residential',
    description: 'Romanian residential proxies — high pool density, rotating IPs, great for scraping.',
    type: 'residential', protocols: ['http', 'https', 'socks5'],
    countryCode: 'RO', countryName: 'Romania', city: 'Bucharest', ispName: 'RCS & RDS',
    speedMbps: 90, uptimePercent: 99.2, stock: -1, isActive: true, isFeatured: false,
    tags: ['residential', 'romania', 'eastern-europe', 'scraping'],
    plans: plans(['2.99','8.99','24.99','59.99','109.99','179.99'], [5,10,20,50,100,200]),
  },
  {
    name: 'TR Residential',
    description: 'Turkish residential proxies bridging Europe and Asia. Access Turkish digital market.',
    type: 'residential', protocols: ['http', 'https', 'socks5'],
    countryCode: 'TR', countryName: 'Turkey', city: 'Istanbul', ispName: 'Turk Telekom',
    speedMbps: 70, uptimePercent: 98.7, stock: -1, isActive: true, isFeatured: false,
    tags: ['residential', 'turkey', 'eurasia'],
    plans: plans(['3.49','10.49','27.99','69.99','124.99','204.99'], [5,5,10,25,50,100]),
  },
  // ─── ASIA ───────────────────────────────────────────────────────
  {
    name: 'SG Datacenter Premium',
    description: 'Singapore datacenter — the hub of Southeast Asia. Ultra-low latency for APAC operations.',
    type: 'datacenter', protocols: ['http', 'https', 'socks5'],
    countryCode: 'SG', countryName: 'Singapore', city: 'Singapore', ispName: 'Singtel',
    speedMbps: 2000, uptimePercent: 99.97, stock: 300, isActive: true, isFeatured: true,
    tags: ['datacenter', 'singapore', 'apac', 'low-latency'],
    plans: plans(['3.49','10.99','28.99','72.99','129.99','214.99'], [10,20,50,100,200,500]),
  },
  {
    name: 'KR Mobile 5G',
    description: 'South Korean 5G mobile proxies. Fastest mobile network in the world, perfect for K-market access.',
    type: 'mobile', protocols: ['http', 'https', 'socks5'],
    countryCode: 'KR', countryName: 'South Korea', city: 'Seoul', ispName: 'SK Telecom',
    speedMbps: 300, uptimePercent: 99.3, stock: 100, isActive: true, isFeatured: true,
    tags: ['mobile', '5g', 'korea', 'ultra-fast'],
    plans: plans(['8.99','27.99','84.99','209.99','379.99','649.99'], [2,5,10,20,40,80]),
  },
  {
    name: 'IN Residential',
    description: 'Indian residential proxies. Access the world largest internet market with real local IPs.',
    type: 'residential', protocols: ['http', 'https', 'socks5'],
    countryCode: 'IN', countryName: 'India', city: 'Mumbai', ispName: 'Jio',
    speedMbps: 40, uptimePercent: 98.2, stock: -1, isActive: true, isFeatured: false,
    tags: ['residential', 'india', 'south-asia', 'large-pool'],
    plans: plans(['2.49','7.49','19.99','49.99','89.99','149.99'], [5,10,20,50,100,200]),
  },
  {
    name: 'HK ISP',
    description: 'Hong Kong ISP proxies — gateway to China and East Asia markets with high reliability.',
    type: 'isp', protocols: ['http', 'https'],
    countryCode: 'HK', countryName: 'Hong Kong', city: 'Hong Kong', ispName: 'HGC',
    speedMbps: 800, uptimePercent: 99.8, stock: 120, isActive: true, isFeatured: false,
    tags: ['isp', 'hong-kong', 'china-gateway', 'east-asia'],
    plans: plans(['6.99','19.99','52.99','129.99','234.99','389.99'], [5,10,20,50,100,200]),
  },
  {
    name: 'TH Mobile 4G',
    description: 'Thai 4G mobile proxies for Southeast Asian operations and local marketplace access.',
    type: 'mobile', protocols: ['http', 'https', 'socks5'],
    countryCode: 'TH', countryName: 'Thailand', city: 'Bangkok', ispName: 'AIS',
    speedMbps: 60, uptimePercent: 98.0, stock: 80, isActive: true, isFeatured: false,
    tags: ['mobile', 'thailand', 'southeast-asia', '4g'],
    plans: plans(['5.99','17.99','49.99','124.99','224.99','384.99'], [2,5,10,20,40,80]),
  },
  {
    name: 'ID Residential',
    description: 'Indonesian residential proxies for the world 4th largest population market.',
    type: 'residential', protocols: ['http', 'https', 'socks5'],
    countryCode: 'ID', countryName: 'Indonesia', city: 'Jakarta', ispName: 'Telkomsel',
    speedMbps: 35, uptimePercent: 97.8, stock: -1, isActive: true, isFeatured: false,
    tags: ['residential', 'indonesia', 'southeast-asia'],
    plans: plans(['2.49','7.49','19.99','49.99','89.99','149.99'], [5,10,20,50,100,200]),
  },
  {
    name: 'AE Datacenter',
    description: 'UAE datacenter proxies for Middle East operations, finance, and regional e-commerce.',
    type: 'datacenter', protocols: ['http', 'https', 'socks5'],
    countryCode: 'AE', countryName: 'UAE', city: 'Dubai', ispName: 'Du',
    speedMbps: 1000, uptimePercent: 99.7, stock: 200, isActive: true, isFeatured: false,
    tags: ['datacenter', 'uae', 'middle-east', 'dubai'],
    plans: plans(['3.99','11.99','31.99','79.99','144.99','239.99'], [10,20,50,100,200,400]),
  },
  {
    name: 'IL Residential',
    description: 'Israeli residential proxies for Middle East and Mediterranean targeting.',
    type: 'residential', protocols: ['http', 'https', 'socks5'],
    countryCode: 'IL', countryName: 'Israel', city: 'Tel Aviv', ispName: 'Bezeq',
    speedMbps: 80, uptimePercent: 99.1, stock: -1, isActive: true, isFeatured: false,
    tags: ['residential', 'israel', 'middle-east'],
    plans: plans(['4.49','13.49','35.99','89.99','159.99','264.99'], [5,5,10,25,50,100]),
  },
  // ─── AFRICA ─────────────────────────────────────────────────────
  {
    name: 'ZA Residential',
    description: 'South African residential proxies. Access African markets, local content and regional services.',
    type: 'residential', protocols: ['http', 'https', 'socks5'],
    countryCode: 'ZA', countryName: 'South Africa', city: 'Cape Town', ispName: 'MTN',
    speedMbps: 30, uptimePercent: 97.5, stock: -1, isActive: true, isFeatured: false,
    tags: ['residential', 'south-africa', 'africa'],
    plans: plans(['2.99','8.99','23.99','59.99','109.99','179.99'], [5,5,10,25,50,100]),
  },
  {
    name: 'EG Residential',
    description: 'Egyptian residential proxies for North African and Middle Eastern market access.',
    type: 'residential', protocols: ['http', 'https', 'socks5'],
    countryCode: 'EG', countryName: 'Egypt', city: 'Cairo', ispName: 'Vodafone EG',
    speedMbps: 25, uptimePercent: 97.0, stock: -1, isActive: true, isFeatured: false,
    tags: ['residential', 'egypt', 'north-africa', 'middle-east'],
    plans: plans(['2.49','7.49','19.99','49.99','89.99','149.99'], [5,5,10,25,50,100]),
  },
  {
    name: 'NG Residential',
    description: 'Nigerian residential proxies — largest economy in Africa, access to West African digital market.',
    type: 'residential', protocols: ['http', 'https', 'socks5'],
    countryCode: 'NG', countryName: 'Nigeria', city: 'Lagos', ispName: 'MTN NG',
    speedMbps: 20, uptimePercent: 96.5, stock: -1, isActive: true, isFeatured: false,
    tags: ['residential', 'nigeria', 'west-africa'],
    plans: plans(['2.49','7.49','19.99','49.99','89.99','149.99'], [5,5,10,25,50,100]),
  },
  // ─── MORE EUROPE ───────────────────────────────────────────────
  {
    name: 'CZ Residential',
    description: 'Czech residential proxies for Central European targeting and local market research.',
    type: 'residential', protocols: ['http', 'https', 'socks5'],
    countryCode: 'CZ', countryName: 'Czech Republic', city: 'Prague', ispName: 'O2 CZ',
    speedMbps: 90, uptimePercent: 99.3, stock: -1, isActive: true, isFeatured: false,
    tags: ['residential', 'czech', 'central-europe'],
    plans: plans(['3.79','11.49','30.99','77.99','139.99','229.99'], [5,5,10,25,50,100]),
  },
  {
    name: 'AT Datacenter',
    description: 'Austrian datacenter proxies in Vienna. Fast EU operations with GDPR compliance.',
    type: 'datacenter', protocols: ['http', 'https', 'socks5'],
    countryCode: 'AT', countryName: 'Austria', city: 'Vienna', ispName: 'A1 Telekom',
    speedMbps: 1000, uptimePercent: 99.8, stock: 300, isActive: true, isFeatured: false,
    tags: ['datacenter', 'austria', 'europe', 'gdpr'],
    plans: plans(['2.99','9.49','24.99','62.99','114.99','189.99'], [10,25,50,100,200,400]),
  },
  {
    name: 'BE Residential',
    description: 'Belgian residential proxies for Benelux market access and EU geo-targeting.',
    type: 'residential', protocols: ['http', 'https', 'socks5'],
    countryCode: 'BE', countryName: 'Belgium', city: 'Brussels', ispName: 'Proximus',
    speedMbps: 85, uptimePercent: 99.2, stock: -1, isActive: true, isFeatured: false,
    tags: ['residential', 'belgium', 'benelux', 'europe'],
    plans: plans(['4.29','12.99','34.99','86.99','154.99','254.99'], [5,5,10,25,50,100]),
  },
  {
    name: 'DK Datacenter',
    description: 'Danish datacenter proxies in Copenhagen. Scandinavia hub with excellent connectivity.',
    type: 'datacenter', protocols: ['http', 'https', 'socks5'],
    countryCode: 'DK', countryName: 'Denmark', city: 'Copenhagen', ispName: 'TDC',
    speedMbps: 1000, uptimePercent: 99.87, stock: 300, isActive: true, isFeatured: false,
    tags: ['datacenter', 'denmark', 'scandinavia'],
    plans: plans(['2.79','8.99','23.99','59.99','109.99','179.99'], [10,25,50,100,200,400]),
  },
  {
    name: 'FI Residential',
    description: 'Finnish residential proxies for Scandinavian and Baltic market operations.',
    type: 'residential', protocols: ['http', 'https', 'socks5'],
    countryCode: 'FI', countryName: 'Finland', city: 'Helsinki', ispName: 'Elisa',
    speedMbps: 100, uptimePercent: 99.4, stock: -1, isActive: true, isFeatured: false,
    tags: ['residential', 'finland', 'scandinavia'],
    plans: plans(['3.79','11.49','30.99','77.99','139.99','229.99'], [5,5,10,25,50,100]),
  },
  {
    name: 'NO Residential',
    description: 'Norwegian residential proxies for North Sea region and Scandinavian targeting.',
    type: 'residential', protocols: ['http', 'https', 'socks5'],
    countryCode: 'NO', countryName: 'Norway', city: 'Oslo', ispName: 'Telenor',
    speedMbps: 100, uptimePercent: 99.5, stock: -1, isActive: true, isFeatured: false,
    tags: ['residential', 'norway', 'scandinavia'],
    plans: plans(['4.49','13.49','35.99','89.99','159.99','264.99'], [5,5,10,25,50,100]),
  },
  {
    name: 'PT Residential',
    description: 'Portuguese residential proxies for Iberian Peninsula and PALOP market access.',
    type: 'residential', protocols: ['http', 'https', 'socks5'],
    countryCode: 'PT', countryName: 'Portugal', city: 'Lisbon', ispName: 'NOS',
    speedMbps: 80, uptimePercent: 99.0, stock: -1, isActive: true, isFeatured: false,
    tags: ['residential', 'portugal', 'iberia'],
    plans: plans(['3.49','10.49','27.99','69.99','124.99','204.99'], [5,5,10,25,50,100]),
  },
  {
    name: 'GR Residential',
    description: 'Greek residential proxies for Mediterranean and Balkans regional operations.',
    type: 'residential', protocols: ['http', 'https', 'socks5'],
    countryCode: 'GR', countryName: 'Greece', city: 'Athens', ispName: 'OTE',
    speedMbps: 70, uptimePercent: 98.8, stock: -1, isActive: true, isFeatured: false,
    tags: ['residential', 'greece', 'mediterranean'],
    plans: plans(['3.29','9.99','26.99','67.99','119.99','199.99'], [5,5,10,25,50,100]),
  },
  {
    name: 'HU Residential',
    description: 'Hungarian residential proxies for Central Eastern Europe market access.',
    type: 'residential', protocols: ['http', 'https', 'socks5'],
    countryCode: 'HU', countryName: 'Hungary', city: 'Budapest', ispName: 'Magyar Telekom',
    speedMbps: 85, uptimePercent: 99.1, stock: -1, isActive: true, isFeatured: false,
    tags: ['residential', 'hungary', 'central-europe'],
    plans: plans(['3.29','9.99','26.99','67.99','119.99','199.99'], [5,5,10,25,50,100]),
  },
  {
    name: 'SK Residential',
    description: 'Slovak residential proxies for Central European and Visegrad group targeting.',
    type: 'residential', protocols: ['http', 'https', 'socks5'],
    countryCode: 'SK', countryName: 'Slovakia', city: 'Bratislava', ispName: 'Slovak Telekom',
    speedMbps: 80, uptimePercent: 99.0, stock: -1, isActive: true, isFeatured: false,
    tags: ['residential', 'slovakia', 'central-europe'],
    plans: plans(['3.29','9.99','26.99','67.99','119.99','199.99'], [5,5,10,25,50,100]),
  },
  {
    name: 'RS Residential',
    description: 'Serbian residential proxies for Balkans region access and local market research.',
    type: 'residential', protocols: ['http', 'https', 'socks5'],
    countryCode: 'RS', countryName: 'Serbia', city: 'Belgrade', ispName: 'Telekom Srbija',
    speedMbps: 75, uptimePercent: 98.7, stock: -1, isActive: true, isFeatured: false,
    tags: ['residential', 'serbia', 'balkans'],
    plans: plans(['2.99','8.99','23.99','59.99','109.99','179.99'], [5,5,10,25,50,100]),
  },
  {
    name: 'BG Residential',
    description: 'Bulgarian residential proxies for Southeast European and Black Sea region operations.',
    type: 'residential', protocols: ['http', 'https', 'socks5'],
    countryCode: 'BG', countryName: 'Bulgaria', city: 'Sofia', ispName: 'Vivacom',
    speedMbps: 80, uptimePercent: 98.9, stock: -1, isActive: true, isFeatured: false,
    tags: ['residential', 'bulgaria', 'eastern-europe'],
    plans: plans(['2.99','8.99','23.99','59.99','109.99','179.99'], [5,5,10,25,50,100]),
  },
  {
    name: 'HR Residential',
    description: 'Croatian residential proxies for Adriatic and Balkans targeting.',
    type: 'residential', protocols: ['http', 'https', 'socks5'],
    countryCode: 'HR', countryName: 'Croatia', city: 'Zagreb', ispName: 'HT',
    speedMbps: 75, uptimePercent: 98.8, stock: -1, isActive: true, isFeatured: false,
    tags: ['residential', 'croatia', 'balkans'],
    plans: plans(['3.29','9.99','26.99','67.99','119.99','199.99'], [5,5,10,25,50,100]),
  },
  {
    name: 'RU Residential',
    description: 'Russian residential proxies from Moscow and Saint Petersburg. Large IP pool.',
    type: 'residential', protocols: ['http', 'https', 'socks5'],
    countryCode: 'RU', countryName: 'Russia', city: 'Moscow', ispName: 'MTS',
    speedMbps: 100, uptimePercent: 99.0, stock: -1, isActive: true, isFeatured: false,
    tags: ['residential', 'russia', 'eastern-europe'],
    plans: plans(['3.49','10.49','27.99','69.99','124.99','204.99'], [5,5,10,25,50,100]),
  },
  // ─── MORE ASIA ──────────────────────────────────────────────────
  {
    name: 'CN Datacenter',
    description: 'Chinese datacenter proxies in Shanghai. Access Chinese digital market with high-speed IPs.',
    type: 'datacenter', protocols: ['http', 'https', 'socks5'],
    countryCode: 'CN', countryName: 'China', city: 'Shanghai', ispName: 'China Unicom',
    speedMbps: 1000, uptimePercent: 99.7, stock: 200, isActive: true, isFeatured: true,
    tags: ['datacenter', 'china', 'east-asia'],
    plans: plans(['7.99','23.99','62.99','154.99','279.99','464.99'], [5,10,25,50,100,200]),
  },
  {
    name: 'VN Residential',
    description: 'Vietnamese residential proxies for Southeast Asian e-commerce and local market access.',
    type: 'residential', protocols: ['http', 'https', 'socks5'],
    countryCode: 'VN', countryName: 'Vietnam', city: 'Ho Chi Minh City', ispName: 'Viettel',
    speedMbps: 45, uptimePercent: 98.2, stock: -1, isActive: true, isFeatured: false,
    tags: ['residential', 'vietnam', 'southeast-asia'],
    plans: plans(['2.49','7.49','19.99','49.99','89.99','149.99'], [5,10,20,50,100,200]),
  },
  {
    name: 'PH Mobile 4G',
    description: 'Philippine 4G mobile proxies for Southeast Asian operations and local app access.',
    type: 'mobile', protocols: ['http', 'https', 'socks5'],
    countryCode: 'PH', countryName: 'Philippines', city: 'Manila', ispName: 'Globe Telecom',
    speedMbps: 40, uptimePercent: 97.5, stock: 80, isActive: true, isFeatured: false,
    tags: ['mobile', 'philippines', 'southeast-asia', '4g'],
    plans: plans(['4.99','14.99','39.99','99.99','179.99','299.99'], [2,5,10,20,40,80]),
  },
  {
    name: 'MY Residential',
    description: 'Malaysian residential proxies for Southeast Asian market targeting and e-commerce.',
    type: 'residential', protocols: ['http', 'https', 'socks5'],
    countryCode: 'MY', countryName: 'Malaysia', city: 'Kuala Lumpur', ispName: 'Celcom',
    speedMbps: 50, uptimePercent: 98.5, stock: -1, isActive: true, isFeatured: false,
    tags: ['residential', 'malaysia', 'southeast-asia'],
    plans: plans(['2.99','8.99','23.99','59.99','109.99','179.99'], [5,10,20,50,100,200]),
  },
  {
    name: 'TW Datacenter',
    description: 'Taiwanese datacenter proxies in Taipei. Ultra-fast for East Asian operations.',
    type: 'datacenter', protocols: ['http', 'https', 'socks5'],
    countryCode: 'TW', countryName: 'Taiwan', city: 'Taipei', ispName: 'Chunghwa Telecom',
    speedMbps: 2000, uptimePercent: 99.9, stock: 250, isActive: true, isFeatured: false,
    tags: ['datacenter', 'taiwan', 'east-asia', 'high-speed'],
    plans: plans(['3.99','11.99','31.99','79.99','144.99','239.99'], [10,20,50,100,200,400]),
  },
  {
    name: 'SA Datacenter',
    description: 'Saudi Arabia datacenter proxies in Riyadh. Best for GCC region and Middle East.',
    type: 'datacenter', protocols: ['http', 'https', 'socks5'],
    countryCode: 'SA', countryName: 'Saudi Arabia', city: 'Riyadh', ispName: 'STC',
    speedMbps: 1000, uptimePercent: 99.6, stock: 200, isActive: true, isFeatured: false,
    tags: ['datacenter', 'saudi-arabia', 'middle-east', 'gcc'],
    plans: plans(['4.49','13.49','35.99','89.99','159.99','264.99'], [10,20,50,100,200,400]),
  },
  {
    name: 'PK Residential',
    description: 'Pakistani residential proxies for South Asian market access and local operations.',
    type: 'residential', protocols: ['http', 'https', 'socks5'],
    countryCode: 'PK', countryName: 'Pakistan', city: 'Karachi', ispName: 'Jazz',
    speedMbps: 25, uptimePercent: 97.0, stock: -1, isActive: true, isFeatured: false,
    tags: ['residential', 'pakistan', 'south-asia'],
    plans: plans(['1.99','5.99','15.99','39.99','71.99','119.99'], [5,10,20,50,100,200]),
  },
  {
    name: 'KZ Residential',
    description: 'Kazakhstani residential proxies for Central Asian market and CIS region access.',
    type: 'residential', protocols: ['http', 'https', 'socks5'],
    countryCode: 'KZ', countryName: 'Kazakhstan', city: 'Almaty', ispName: 'Kazakhtelecom',
    speedMbps: 50, uptimePercent: 98.0, stock: -1, isActive: true, isFeatured: false,
    tags: ['residential', 'kazakhstan', 'central-asia'],
    plans: plans(['2.49','7.49','19.99','49.99','89.99','149.99'], [5,10,20,50,100,200]),
  },
  {
    name: 'UZ Residential',
    description: 'Uzbekistani residential proxies for Central Asian operations and local market.',
    type: 'residential', protocols: ['http', 'https', 'socks5'],
    countryCode: 'UZ', countryName: 'Uzbekistan', city: 'Tashkent', ispName: 'Ucell',
    speedMbps: 40, uptimePercent: 97.5, stock: -1, isActive: true, isFeatured: false,
    tags: ['residential', 'uzbekistan', 'central-asia'],
    plans: plans(['1.99','5.99','15.99','39.99','71.99','119.99'], [5,10,20,50,100,200]),
  },
  {
    name: 'BD Residential',
    description: 'Bangladeshi residential proxies for South Asian digital market access.',
    type: 'residential', protocols: ['http', 'https', 'socks5'],
    countryCode: 'BD', countryName: 'Bangladesh', city: 'Dhaka', ispName: 'Grameenphone',
    speedMbps: 20, uptimePercent: 96.5, stock: -1, isActive: true, isFeatured: false,
    tags: ['residential', 'bangladesh', 'south-asia'],
    plans: plans(['1.49','4.49','11.99','29.99','53.99','89.99'], [5,10,20,50,100,200]),
  },
  // ─── MORE AMERICAS ──────────────────────────────────────────────
  {
    name: 'AR Residential',
    description: 'Argentine residential proxies for South American market access and LATAM operations.',
    type: 'residential', protocols: ['http', 'https', 'socks5'],
    countryCode: 'AR', countryName: 'Argentina', city: 'Buenos Aires', ispName: 'Fibertel',
    speedMbps: 50, uptimePercent: 98.0, stock: -1, isActive: true, isFeatured: false,
    tags: ['residential', 'argentina', 'south-america', 'latam'],
    plans: plans(['2.99','8.99','23.99','59.99','109.99','179.99'], [5,10,20,50,100,200]),
  },
  {
    name: 'CL Residential',
    description: 'Chilean residential proxies for South American and Pacific Rim targeting.',
    type: 'residential', protocols: ['http', 'https', 'socks5'],
    countryCode: 'CL', countryName: 'Chile', city: 'Santiago', ispName: 'Movistar CL',
    speedMbps: 60, uptimePercent: 98.5, stock: -1, isActive: true, isFeatured: false,
    tags: ['residential', 'chile', 'south-america'],
    plans: plans(['3.29','9.99','26.99','67.99','119.99','199.99'], [5,10,20,50,100,200]),
  },
  {
    name: 'CO Residential',
    description: 'Colombian residential proxies for Andean and Caribbean market access.',
    type: 'residential', protocols: ['http', 'https', 'socks5'],
    countryCode: 'CO', countryName: 'Colombia', city: 'Bogotá', ispName: 'Claro CO',
    speedMbps: 45, uptimePercent: 97.8, stock: -1, isActive: true, isFeatured: false,
    tags: ['residential', 'colombia', 'south-america', 'latam'],
    plans: plans(['2.49','7.49','19.99','49.99','89.99','149.99'], [5,10,20,50,100,200]),
  },
  {
    name: 'PE Residential',
    description: 'Peruvian residential proxies for Andean market and South American operations.',
    type: 'residential', protocols: ['http', 'https', 'socks5'],
    countryCode: 'PE', countryName: 'Peru', city: 'Lima', ispName: 'Claro PE',
    speedMbps: 40, uptimePercent: 97.5, stock: -1, isActive: true, isFeatured: false,
    tags: ['residential', 'peru', 'south-america'],
    plans: plans(['2.49','7.49','19.99','49.99','89.99','149.99'], [5,10,20,50,100,200]),
  },
  // ─── MORE AFRICA ────────────────────────────────────────────────
  {
    name: 'KE Mobile 4G',
    description: 'Kenyan 4G mobile proxies powered by Safaricom — Africa\'s leading mobile network.',
    type: 'mobile', protocols: ['http', 'https', 'socks5'],
    countryCode: 'KE', countryName: 'Kenya', city: 'Nairobi', ispName: 'Safaricom',
    speedMbps: 30, uptimePercent: 97.0, stock: 60, isActive: true, isFeatured: false,
    tags: ['mobile', 'kenya', 'east-africa', '4g'],
    plans: plans(['3.49','10.49','27.99','69.99','124.99','204.99'], [2,5,10,20,40,80]),
  },
  {
    name: 'MA Residential',
    description: 'Moroccan residential proxies for North African and Maghreb market access.',
    type: 'residential', protocols: ['http', 'https', 'socks5'],
    countryCode: 'MA', countryName: 'Morocco', city: 'Casablanca', ispName: 'Maroc Telecom',
    speedMbps: 25, uptimePercent: 97.0, stock: -1, isActive: true, isFeatured: false,
    tags: ['residential', 'morocco', 'north-africa'],
    plans: plans(['2.49','7.49','19.99','49.99','89.99','149.99'], [5,5,10,25,50,100]),
  },
  {
    name: 'GH Residential',
    description: 'Ghanaian residential proxies for West African market and regional operations.',
    type: 'residential', protocols: ['http', 'https', 'socks5'],
    countryCode: 'GH', countryName: 'Ghana', city: 'Accra', ispName: 'MTN GH',
    speedMbps: 20, uptimePercent: 96.5, stock: -1, isActive: true, isFeatured: false,
    tags: ['residential', 'ghana', 'west-africa'],
    plans: plans(['1.99','5.99','15.99','39.99','71.99','119.99'], [5,5,10,25,50,100]),
  },
  {
    name: 'TZ Residential',
    description: 'Tanzanian residential proxies for East African market access and local operations.',
    type: 'residential', protocols: ['http', 'https', 'socks5'],
    countryCode: 'TZ', countryName: 'Tanzania', city: 'Dar es Salaam', ispName: 'Vodacom TZ',
    speedMbps: 15, uptimePercent: 96.0, stock: -1, isActive: true, isFeatured: false,
    tags: ['residential', 'tanzania', 'east-africa'],
    plans: plans(['1.99','5.99','15.99','39.99','71.99','119.99'], [5,5,10,25,50,100]),
  },
  // ─── OCEANIA ───────────────────────────────────────────────────
  {
    name: 'NZ Residential',
    description: 'New Zealand residential proxies for Oceania market access and APAC targeting.',
    type: 'residential', protocols: ['http', 'https', 'socks5'],
    countryCode: 'NZ', countryName: 'New Zealand', city: 'Auckland', ispName: 'Spark NZ',
    speedMbps: 80, uptimePercent: 99.0, stock: -1, isActive: true, isFeatured: false,
    tags: ['residential', 'new-zealand', 'oceania', 'apac'],
    plans: plans(['4.99','14.99','39.99','99.99','179.99','299.99'], [5,5,10,25,50,100]),
  },
  {
    name: 'AU Residential',
    description: 'Australian residential proxies for APAC-Oceania targeting, local content and market research.',
    type: 'residential', protocols: ['http', 'https', 'socks5'],
    countryCode: 'AU', countryName: 'Australia', city: 'Sydney', ispName: 'Telstra',
    speedMbps: 80, uptimePercent: 99.1, stock: -1, isActive: true, isFeatured: false,
    tags: ['residential', 'australia', 'oceania', 'apac'],
    plans: plans(['4.99','14.99','39.99','99.99','179.99','299.99'], [5,5,10,25,50,100]),
  },
  {
    name: 'AU Datacenter',
    description: 'Australian datacenter proxies — fast and reliable for Oceania and Pacific operations.',
    type: 'datacenter', protocols: ['http', 'https', 'socks5'],
    countryCode: 'AU', countryName: 'Australia', city: 'Melbourne', ispName: 'Optus',
    speedMbps: 1000, uptimePercent: 99.85, stock: 250, isActive: true, isFeatured: false,
    tags: ['datacenter', 'australia', 'oceania'],
    plans: plans(['2.99','8.99','23.99','59.99','109.99','179.99'], [10,25,50,100,200,400]),
  },
]

const EXTRA_COUNTRIES = [
  // ─── EUROPE ───────────────────────────────────────────────────────────────
  res('IE', 'Ireland',              'Dublin',              'Eircom',            100, 99.5, 39.99),
  res('IS', 'Iceland',              'Reykjavik',           'Siminn',            100, 99.4, 34.99),
  res('LT', 'Lithuania',            'Vilnius',             'Telia LT',           90, 99.3, 29.99),
  res('LV', 'Latvia',               'Riga',                'LMT',                90, 99.2, 29.99),
  res('EE', 'Estonia',              'Tallinn',             'Telia EE',          100, 99.4, 31.99),
  res('LU', 'Luxembourg',           'Luxembourg City',     'POST Luxembourg',   100, 99.6, 39.99),
  res('MT', 'Malta',                'Valletta',            'GO Mobile',          80, 99.0, 31.99),
  res('CY', 'Cyprus',               'Nicosia',             'Cyta',               80, 98.8, 27.99),
  res('AL', 'Albania',              'Tirana',              'Vodafone AL',        60, 98.3, 22.99),
  res('BA', 'Bosnia & Herzegovina', 'Sarajevo',            'BH Telecom',         60, 98.2, 22.99),
  res('BY', 'Belarus',              'Minsk',               'A1 BY',              80, 98.5, 23.99),
  res('MD', 'Moldova',              'Chisinau',            'Moldtelecom',        60, 97.8, 19.99),
  res('ME', 'Montenegro',           'Podgorica',           'T-Mobile ME',        60, 97.8, 22.99),
  res('MK', 'North Macedonia',      'Skopje',              'Makedonski Telekom', 60, 98.0, 21.99),
  res('SI', 'Slovenia',             'Ljubljana',           'Telekom SI',         90, 99.2, 32.99),
  res('GE', 'Georgia',              'Tbilisi',             'Magti',              70, 98.5, 22.99),
  res('AM', 'Armenia',              'Yerevan',             'VivaCell-MTS',       60, 98.0, 21.99),
  res('AZ', 'Azerbaijan',           'Baku',                'Azercell',           70, 98.2, 23.99),
  res('AD', 'Andorra',              'Andorra la Vella',    'Andorra Telecom',    80, 99.0, 27.99),
  res('LI', 'Liechtenstein',        'Vaduz',               'Telecom LI',         80, 99.1, 34.99),
  res('SM', 'San Marino',           'San Marino',          'TIM',                80, 98.8, 27.99),
  res('XK', 'Kosovo',               'Pristina',            'IPKO',               60, 98.0, 21.99),
  // ─── MIDDLE EAST ──────────────────────────────────────────────────────────
  res('IQ', 'Iraq',                 'Baghdad',             'Zain IQ',            30, 96.5, 21.99),
  res('IR', 'Iran',                 'Tehran',              'Hamrahe Aval',       40, 97.0, 21.99),
  res('JO', 'Jordan',               'Amman',               'Zain JO',            50, 97.5, 23.99),
  res('KW', 'Kuwait',               'Kuwait City',         'Ooredoo KW',         80, 98.5, 29.99),
  res('LB', 'Lebanon',              'Beirut',              'Alfa',               40, 96.0, 19.99),
  res('OM', 'Oman',                 'Muscat',              'Omantel',            70, 98.0, 27.99),
  res('QA', 'Qatar',                'Doha',                'Ooredoo QA',        100, 99.0, 29.99),
  res('YE', 'Yemen',                'Sanaa',               'MTN YE',             15, 94.0, 17.99),
  res('BH', 'Bahrain',              'Manama',              'Batelco',            80, 98.5, 27.99),
  res('PS', 'Palestine',            'Ramallah',            'Paltel',             30, 95.5, 17.99),
  res('SY', 'Syria',                'Damascus',            'MTN SY',             20, 94.5, 16.99),
  // ─── AFRICA ────────────────────────────────────────────────────────────────
  res('DZ', 'Algeria',              'Algiers',             'Djezzy',             30, 97.0, 19.99),
  res('AO', 'Angola',               'Luanda',              'Unitel',             25, 96.5, 17.99),
  res('BI', 'Burundi',              'Bujumbura',           'Leo',                10, 93.0, 11.99),
  res('BJ', 'Benin',                'Cotonou',             'MTN BJ',             15, 94.5, 13.99),
  res('BW', 'Botswana',             'Gaborone',            'BTC',                25, 96.0, 16.99),
  res('BF', 'Burkina Faso',         'Ouagadougou',         'Orange BF',          15, 94.0, 13.99),
  res('CM', 'Cameroon',             'Yaounde',             'Orange CM',          20, 95.5, 15.99),
  res('CF', 'Central African Rep.', 'Bangui',              'Orange CF',           8, 91.0, 11.99),
  res('CG', 'Republic of Congo',    'Brazzaville',         'MTN CG',             15, 94.5, 13.99),
  res('CD', 'DR Congo',             'Kinshasa',            'Airtel CD',          10, 93.0, 12.99),
  res('CI', 'Ivory Coast',          'Abidjan',             'Orange CI',          25, 96.0, 17.99),
  res('CV', 'Cape Verde',           'Praia',               'CV Movel',           30, 96.5, 17.99),
  res('DJ', 'Djibouti',             'Djibouti City',       'Evatis',             20, 95.0, 15.99),
  res('ER', 'Eritrea',              'Asmara',              'Eritel',              8, 90.0, 11.99),
  res('ET', 'Ethiopia',             'Addis Ababa',         'Ethio Telecom',      15, 94.0, 13.99),
  res('GA', 'Gabon',                'Libreville',          'Airtel GA',          25, 96.0, 16.99),
  res('GM', 'Gambia',               'Banjul',              'Africell',           15, 94.0, 13.99),
  res('GN', 'Guinea',               'Conakry',             'Orange GN',          15, 93.5, 13.99),
  res('GQ', 'Equatorial Guinea',    'Malabo',              'HiTs EG',            15, 93.5, 13.99),
  res('GW', 'Guinea-Bissau',        'Bissau',              'MTN GW',             10, 92.0, 11.99),
  res('KM', 'Comoros',              'Moroni',              'Comores Telecom',    10, 92.5, 12.99),
  res('LS', 'Lesotho',              'Maseru',              'Vodacom LS',         20, 95.0, 15.99),
  res('LR', 'Liberia',              'Monrovia',            'Orange LR',          15, 93.5, 13.99),
  res('LY', 'Libya',                'Tripoli',             'Libyana',            20, 94.0, 16.99),
  res('MG', 'Madagascar',           'Antananarivo',        'Orange MG',          15, 94.0, 13.99),
  res('ML', 'Mali',                 'Bamako',              'Orange ML',          15, 93.5, 13.99),
  res('MR', 'Mauritania',           'Nouakchott',          'Mauritel',           15, 93.5, 13.99),
  res('MU', 'Mauritius',            'Port Louis',          'Emtel',              40, 97.0, 19.99),
  res('MW', 'Malawi',               'Lilongwe',            'Airtel MW',          15, 93.5, 13.99),
  res('MZ', 'Mozambique',           'Maputo',              'Vodacom MZ',         20, 95.0, 15.99),
  res('NA', 'Namibia',              'Windhoek',            'MTC NA',             25, 96.0, 16.99),
  res('NE', 'Niger',                'Niamey',              'Airtel NE',          10, 92.5, 11.99),
  res('RW', 'Rwanda',               'Kigali',              'MTN RW',             30, 96.5, 15.99),
  res('SD', 'Sudan',                'Khartoum',            'MTN SD',             20, 94.5, 15.99),
  res('SL', 'Sierra Leone',         'Freetown',            'Orange SL',          15, 93.0, 13.99),
  res('SN', 'Senegal',              'Dakar',               'Orange SN',          25, 96.0, 17.99),
  res('SO', 'Somalia',              'Mogadishu',           'Somtel',             15, 92.5, 13.99),
  res('SS', 'South Sudan',          'Juba',                'Zain SS',            10, 91.5, 11.99),
  res('ST', 'Sao Tome & Principe',  'Sao Tome',            'CST',                10, 92.0, 12.99),
  res('SZ', 'Eswatini',             'Mbabane',             'MTN SZ',             20, 95.0, 15.99),
  res('TD', 'Chad',                 'N\'Djamena',          'Airtel TD',          10, 91.5, 11.99),
  res('TG', 'Togo',                 'Lome',                'Togocel',            15, 94.0, 13.99),
  res('TN', 'Tunisia',              'Tunis',               'Ooredoo TN',         35, 97.0, 19.99),
  res('UG', 'Uganda',               'Kampala',             'MTN UG',             20, 95.0, 15.99),
  res('ZM', 'Zambia',               'Lusaka',              'Airtel ZM',          20, 95.0, 15.99),
  res('ZW', 'Zimbabwe',             'Harare',              'Econet',             20, 94.5, 15.99),
  // ─── ASIA ─────────────────────────────────────────────────────────────────
  res('AF', 'Afghanistan',          'Kabul',               'Roshan',             15, 92.0, 13.99),
  res('BN', 'Brunei',               'Bandar Seri Begawan', 'DST',                50, 98.0, 23.99),
  res('BT', 'Bhutan',               'Thimphu',             'TashiCell',          20, 94.0, 15.99),
  res('KH', 'Cambodia',             'Phnom Penh',          'Smart Axiata',       30, 96.0, 17.99),
  res('KG', 'Kyrgyzstan',           'Bishkek',             'Beeline KG',         30, 96.0, 17.99),
  res('LA', 'Laos',                 'Vientiane',           'Unitel LA',          25, 95.0, 15.99),
  res('LK', 'Sri Lanka',            'Colombo',             'Dialog',             40, 97.0, 19.99),
  res('MN', 'Mongolia',             'Ulaanbaatar',         'Mobicom',            30, 96.0, 17.99),
  res('MM', 'Myanmar',              'Yangon',              'MPT',                25, 95.5, 15.99),
  res('MO', 'Macau',                'Macau',               'CTM',                80, 99.0, 27.99),
  res('MV', 'Maldives',             'Male',                'Dhiraagu',           30, 97.0, 21.99),
  res('NP', 'Nepal',                'Kathmandu',           'Ncell',              20, 95.0, 15.99),
  res('TJ', 'Tajikistan',           'Dushanbe',            'Tcell',              20, 94.5, 15.99),
  res('TL', 'Timor-Leste',          'Dili',                'Timor Telecom',      15, 93.5, 13.99),
  res('TM', 'Turkmenistan',         'Ashgabat',            'TM Cell',            20, 94.0, 15.99),
  // ─── AMERICAS ─────────────────────────────────────────────────────────────
  res('AG', 'Antigua and Barbuda',  'Saint Johns',         'Digicel AG',         30, 96.5, 19.99),
  res('BB', 'Barbados',             'Bridgetown',          'LIME',               40, 97.0, 21.99),
  res('BZ', 'Belize',               'Belmopan',            'BTL',                25, 95.5, 17.99),
  res('BO', 'Bolivia',              'La Paz',              'Entel BO',           30, 96.0, 19.99),
  res('BS', 'Bahamas',              'Nassau',              'BTC',                40, 97.0, 21.99),
  res('CR', 'Costa Rica',           'San Jose',            'Claro CR',           50, 97.5, 23.99),
  res('CU', 'Cuba',                 'Havana',              'ETECSA',             10, 91.0, 14.99),
  res('CW', 'Curacao',              'Willemstad',          'UTS',                50, 97.5, 21.99),
  res('DM', 'Dominica',             'Roseau',              'Digicel DM',         30, 96.0, 18.99),
  res('DO', 'Dominican Republic',   'Santo Domingo',       'Claro DO',           40, 97.0, 21.99),
  res('EC', 'Ecuador',              'Quito',               'Claro EC',           40, 97.0, 21.99),
  res('GD', 'Grenada',              'St. Georges',         'Digicel GD',         30, 96.0, 18.99),
  res('GT', 'Guatemala',            'Guatemala City',      'Tigo GT',            35, 96.5, 20.99),
  res('GY', 'Guyana',               'Georgetown',          'GT&T',               25, 95.5, 17.99),
  res('HN', 'Honduras',             'Tegucigalpa',         'Tigo HN',            30, 95.5, 19.99),
  res('HT', 'Haiti',                'Port-au-Prince',      'Digicel HT',         15, 93.0, 14.99),
  res('JM', 'Jamaica',              'Kingston',            'Digicel JM',         35, 97.0, 19.99),
  res('KN', 'Saint Kitts and Nevis','Basseterre',          'Digicel KN',         30, 96.0, 18.99),
  res('LC', 'Saint Lucia',          'Castries',            'Digicel LC',         30, 96.5, 18.99),
  res('NI', 'Nicaragua',            'Managua',             'Claro NI',           25, 95.5, 17.99),
  res('PA', 'Panama',               'Panama City',         'Cable & Wireless',   50, 97.5, 23.99),
  res('PR', 'Puerto Rico',          'San Juan',            'T-Mobile PR',        60, 98.0, 26.99),
  res('PY', 'Paraguay',             'Asuncion',            'Tigo PY',            30, 96.0, 19.99),
  res('SR', 'Suriname',             'Paramaribo',          'Telesur',            25, 95.5, 17.99),
  res('SV', 'El Salvador',          'San Salvador',        'Tigo SV',            35, 96.5, 19.99),
  res('TT', 'Trinidad and Tobago',  'Port of Spain',       'TSTT',               40, 97.5, 21.99),
  res('UY', 'Uruguay',              'Montevideo',          'Antel',              50, 98.0, 23.99),
  res('VE', 'Venezuela',            'Caracas',             'Movistar VE',        25, 95.0, 17.99),
  // ─── OCEANIA ──────────────────────────────────────────────────────────────
  res('FJ', 'Fiji',                 'Suva',                'Vodafone FJ',        30, 96.0, 19.99),
  res('FM', 'Micronesia',           'Palikir',             'FSM Telecom',        10, 93.0, 14.99),
  res('KI', 'Kiribati',             'Tarawa',              'Telecom Kiribati',    8, 91.0, 12.99),
  res('MH', 'Marshall Islands',     'Majuro',              'NTSC',               10, 92.5, 13.99),
  res('NR', 'Nauru',                'Yaren',               'RONNet',              8, 91.5, 12.99),
  res('PG', 'Papua New Guinea',     'Port Moresby',        'Digicel PG',         20, 95.0, 16.99),
  res('PW', 'Palau',                'Ngerulmud',           'PNCC',               10, 92.5, 13.99),
  res('SB', 'Solomon Islands',      'Honiara',             'Our Telekom',        10, 92.5, 13.99),
  res('TO', 'Tonga',                'Nukualofa',           'Digicel TO',         15, 93.5, 14.99),
  res('TV', 'Tuvalu',               'Funafuti',            'TTC',                 5, 89.0, 12.99),
  res('VU', 'Vanuatu',              'Port Vila',           'Digicel VU',         15, 93.5, 14.99),
  res('WS', 'Samoa',                'Apia',                'Digicel WS',         15, 93.5, 14.99),
]

function generateReferralCode(): string {
  return Math.random().toString(36).substring(2, 10).toUpperCase()
}

async function seed() {
  await connectDB()
  console.log('Connected to MongoDB')

  // Clean existing data
  await Promise.all([
    User.deleteMany({}),
    ProxyProduct.deleteMany({}),
    UserProxy.deleteMany({}),
    Order.deleteMany({}),
  ])
  console.log('Cleaned existing data')

  // Create admin user
  const adminPassword = await bcrypt.hash('Admin@123456', 12)
  const admin = await User.create({
    email: 'admin@proxyservice.io',
    passwordHash: adminPassword,
    username: 'admin',
    role: 'admin',
    balance: mongoose.Types.Decimal128.fromString('1000.00'),
    referralCode: generateReferralCode(),
    emailVerified: true,
  })
  console.log('Created admin user:', admin.email)

  // Create test user
  const userPassword = await bcrypt.hash('User@123456', 12)
  const testUser = await User.create({
    email: 'user@proxyservice.io',
    passwordHash: userPassword,
    username: 'testuser',
    role: 'user',
    balance: mongoose.Types.Decimal128.fromString('150.00'),
    referralCode: generateReferralCode(),
    emailVerified: true,
  })
  console.log('Created test user:', testUser.email)

  // Create proxy products
  const products = (await ProxyProduct.insertMany([...PRODUCTS_SEED, ...EXTRA_COUNTRIES])) as unknown as ProxyProductDocument[]
  console.log(`Created ${products.length} proxy products`)

  // Create test order and proxies for test user
  const product = products[0]
  const plan = product.plans[2] // 30d plan

  const testOrder = await Order.create({
    userId: testUser._id,
    status: 'completed',
    totalUsdt: mongoose.Types.Decimal128.fromString('39.99'),
    discountUsdt: mongoose.Types.Decimal128.fromString('0'),
    paymentMethod: 'usdt_trc20',
    paymentId: 'test_payment_001',
    paidAt: new Date(),
    items: [
      {
        planId: plan._id,
        productId: product._id,
        quantity: 1,
        priceUsdt: plan.priceUsdt,
        ipCount: plan.ipCount,
      },
    ],
  })

  // Create sample proxies
  const proxyHosts = [
    { host: '185.220.101.45', port: 8080 },
    { host: '185.220.101.46', port: 8080 },
    { host: '185.220.101.47', port: 8080 },
  ]

  const proxies = await UserProxy.insertMany(
    proxyHosts.map((p, i) => ({
      userId: testUser._id,
      productId: product._id,
      orderId: testOrder._id,
      status: i === 0 ? 'active' : 'active',
      host: p.host,
      port: p.port,
      username: `user_${testUser._id.toString().slice(-8)}_${i}`,
      password: 'proxy_pass_encrypted',
      protocol: 'http',
      expiresAt: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
      autoRenew: i === 0,
      replacedCount: 0,
    }))
  )
  console.log(`Created ${proxies.length} sample proxies for test user`)

  console.log('\n=== SEED COMPLETE ===')
  console.log('Admin:    admin@proxyservice.io / Admin@123456')
  console.log('User:     user@proxyservice.io / User@123456')
  console.log(`Products: ${products.length} created`)
  console.log(`Proxies:  ${proxies.length} created for test user`)

  await mongoose.disconnect()
}

seed().catch((err) => {
  console.error('Seed failed:', err)
  process.exit(1)
})
